name = "Ebonysmo"
author = "Daedreus"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09fcc033269d42856adce0d8abf19a1b07a6b9bdbda06ecdf709a0ea2a1c65f9"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
